# Generated by Django 5.0.1 on 2024-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
