# Generated by Django 5.0.1 on 2024-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_remove_users_img_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='user'),
        ),
    ]
