# Generated by Django 5.0.1 on 2024-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
