# Generated by Django 5.0.1 on 2024-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0005_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
